name = "api"
main = "src/worker.ts"
compatibility_date = "2023-05-27"

kv_namespaces = [
  { binding = "VERSIONS", id = "722f0fadd97343ebb8a51c925d1d4316" },
  { binding = "METADATA", id = "49e9d329349446cf948f84af9828914f" },
]

r2_buckets = [
  { binding = "BUCKET", bucket_name = "fonts", preview_bucket_name = "fonts-preview" },
]

logpush = true
workers_dev = false

[triggers]
crons = ["0 */3 * * *"]
