name: 🐛 Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue 🙏.
        Before you submit, please search the issue tracker to prevent duplicates as a similar issue might already exist.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: |
        As a user, I expected ___ behavior but i am seeing ___
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: 4.5.0
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: Linux
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Firefox
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
