"use client";

// Auto-generated by boneyard vite plugin - do not edit
import { registerBones } from 'boneyard-js/react';

import _docs_search_results from './docs-search-results.bones.json';
import _font_preview_row from './font-preview-row.bones.json';
import _search_hit_preview from './search-hit-preview.bones.json';

registerBones({
	'docs-search-results': _docs_search_results,
	'font-preview-row': _font_preview_row,
	'search-hit-preview': _search_hit_preview,
});
