"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _search_hit_preview from './search-hit-preview.bones.json'
import _font_preview_row from './font-preview-row.bones.json'

registerBones({
  "search-hit-preview": _search_hit_preview,
  "font-preview-row": _font_preview_row,
})
