name = "cdn"
main = "src/worker.ts"
compatibility_date = "2023-05-27"

r2_buckets = [
  { binding = "BUCKET", bucket_name = "fonts", preview_bucket_name = "fonts-preview" },
]

logpush = true
workers_dev = false
