name = "cdn"
main = "src/worker.ts"
compatibility_date = "2023-05-27"

kv_namespaces = [{ binding = "CSS", id = "be3369d7d4c345c5bb9139f3c00f7c19" }]

r2_buckets = [
  { binding = "FONTS", bucket_name = "fonts", preview_bucket_name = "fonts-preview" },
]

services = [
  { binding = "METADATA", service = "api", environment = "production" },
]

logpush = true
workers_dev = false

[triggers]
crons = ["0 0 * * *"]

[miniflare.mounts]
api = "../api/"
