name = "cdn"
main = "src/worker.ts"
compatibility_date = "2023-05-27"

r2_buckets = [
  { binding = "BUCKET", bucket_name = "fonts", preview_bucket_name = "fonts-preview" },
]

services = [
  { binding = "DOWNLOAD", service = "download", environment = "production" },
  { binding = "METADATA", service = "api", environment = "production" },
]

logpush = true
workers_dev = false

[miniflare.mounts]
download = "../download/"
api = "../api/"
