# fly.toml app configuration file generated for font-download-vm on 2023-10-02T23:49:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "font-download-vm"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
