import type { ProjectItem } from './model';

const fallbacks: Record<ProjectItem['category'], string> = {
	'sans-serif': 'sans-serif',
	serif: 'serif',
	display: 'serif',
	handwriting: 'cursive',
	monospace: 'monospace',
	icons: 'sans-serif',
	other: 'sans-serif',
};

const getCdnUrl = (item: ProjectItem) =>
	`https://cdn.jsdelivr.net/npm/${item.packageName}@${item.packageVersion}/${item.cssFile}`;

const getFontStack = (item: ProjectItem) => {
	const family = item.fontFamily.replaceAll("'", "\\'");
	if (item.familyId.startsWith('yakuhan')) {
		return `'${family}', 'Noto Sans JP', sans-serif`;
	}
	if (item.familyId.startsWith('dseg')) {
		return `'${family}', monospace`;
	}
	return `'${family}', ${fallbacks[item.category]}`;
};

const getUsageNote = (item: ProjectItem) => {
	if (item.category === 'icons') {
		return 'Use icon names as ligatures, such as “home” or “search”.';
	}
	if (item.familyId.startsWith('yakuhan')) {
		return 'Punctuation only. Keep your Japanese text font immediately after it in the fallback stack.';
	}
	if (item.familyId.startsWith('dseg')) {
		return 'Tabular numerals and a single line keep changing readout values stable.';
	}
};

const getUsageBlock = (item: ProjectItem) => {
	const declarations = [
		`font-family: ${getFontStack(item)};`,
		`font-weight: ${item.weight};`,
		`font-style: ${item.style};`,
	];

	if (Object.keys(item.axes).length > 0) {
		const settings = Object.entries(item.axes)
			.map(([axis, value]) => `'${axis}' ${value}`)
			.join(', ');
		declarations.push(`font-variation-settings: ${settings};`);
	}
	if (item.category === 'icons') {
		declarations.push(
			'line-height: 1;',
			'white-space: nowrap;',
			"font-feature-settings: 'liga';",
		);
	}
	if (item.familyId.startsWith('dseg')) {
		declarations.push(
			'font-variant-numeric: tabular-nums;',
			"font-feature-settings: 'tnum';",
			'white-space: nowrap;',
		);
	}

	return `.font-${item.familyId} {\n${declarations.map((line) => `  ${line}`).join('\n')}\n}`;
};

const getProjectCss = (items: ProjectItem[]) => {
	const licenses = items
		.map(
			(item) =>
				`/* ${item.displayName}: ${
					item.license.verified && item.license.id
						? `${item.license.id} (registry verified)`
						: 'license not verified'
				} */`,
		)
		.join('\n');
	const imports = items
		.map((item) => `@import url('${getCdnUrl(item)}');`)
		.join('\n');
	const usage = items.map(getUsageBlock).join('\n\n');
	return `/* Generated by Fontsource Font Set */\n${licenses}\n${imports}\n\n${usage}\n`;
};

export { getCdnUrl, getFontStack, getProjectCss, getUsageBlock, getUsageNote };
