import { getJsDelivrPackageUrl } from '../../utils/cdn';
import type { ProjectItem } from './model';

const fallbacks: Record<ProjectItem['category'], string> = {
	'sans-serif': 'sans-serif',
	serif: 'serif',
	display: 'serif',
	handwriting: 'cursive',
	monospace: 'monospace',
	icons: 'sans-serif',
	other: 'sans-serif',
};

const getCdnUrl = (item: ProjectItem) =>
	getJsDelivrPackageUrl(item.packageName, item.packageVersion, item.cssFile);

const getSelectedCssFiles = (
	item: Pick<ProjectItem, 'cssFile' | 'format' | 'subset'>,
	styles: ProjectItem['style'][],
	weights: number[],
) => {
	if (item.cssFile === 'full.css') return ['full.css'];
	if (item.format === 'variable') {
		const axisKey = item.cssFile
			.replace(`${item.subset}-`, '')
			.replace('-italic.css', '')
			.replace('.css', '');
		return styles.map(
			(style) =>
				`${item.subset}-${axisKey}${style === 'italic' ? '-italic' : ''}.css`,
		);
	}
	return styles.flatMap((style) =>
		weights.map(
			(weight) =>
				`${item.subset}-${weight}${style === 'italic' ? '-italic' : ''}.css`,
		),
	);
};

const hasTag = (item: ProjectItem, tag: string) => item.tags.includes(tag);
const hasSymbolCatalog = (item: ProjectItem) =>
	item.symbolInputModes.length > 0;
const usesNameLigatures = (item: ProjectItem) =>
	item.symbolInputModes.includes('name-ligature');
const isPunctuationFamily = (item: ProjectItem) =>
	hasTag(item, 'special-use/punctuation');
const isDigitalFamily = (item: ProjectItem) =>
	hasTag(item, 'special-use/digital-display');

const getFontStack = (item: ProjectItem) => {
	const family = item.fontFamily.replaceAll("'", "\\'");
	if (isPunctuationFamily(item)) {
		return `'${family}', 'Noto Sans JP', sans-serif`;
	}
	if (isDigitalFamily(item)) {
		return `'${family}', monospace`;
	}
	return `'${family}', ${fallbacks[item.category]}`;
};

const getUsageNote = (item: ProjectItem) => {
	if (usesNameLigatures(item)) {
		const examples = item.sampleText
			.trim()
			.split(/\s+/)
			.slice(0, 2)
			.join(' or ');
		return examples
			? `Use verified symbol names as ligatures, such as ${examples}.`
			: 'Use verified symbol names from the registry catalog as ligatures.';
	}
	if (isPunctuationFamily(item)) {
		return 'Punctuation only. Keep your Japanese text font immediately after it in the fallback stack.';
	}
	if (isDigitalFamily(item)) {
		return 'Tabular numerals and a single line keep changing readout values stable.';
	}
};

const getUsageBlock = (item: ProjectItem) => {
	const declarations = [
		`font-family: ${getFontStack(item)};`,
		`font-weight: ${item.weight};`,
		`font-style: ${item.style};`,
	];

	if (Object.keys(item.axes).length > 0) {
		const settings = Object.entries(item.axes)
			.map(([axis, value]) => `'${axis}' ${value}`)
			.join(', ');
		declarations.push(`font-variation-settings: ${settings};`);
	}
	if (usesNameLigatures(item)) {
		declarations.push(
			'line-height: 1;',
			'text-transform: none;',
			'white-space: nowrap;',
			"font-feature-settings: 'liga';",
		);
	}
	if (isDigitalFamily(item)) {
		declarations.push(
			'font-variant-numeric: tabular-nums;',
			"font-feature-settings: 'tnum';",
			'white-space: nowrap;',
		);
	}

	return `.font-${item.familyId} {\n${declarations.map((line) => `  ${line}`).join('\n')}\n}`;
};

const escapeHtml = (value: string) =>
	value
		.replaceAll('&', '&amp;')
		.replaceAll('<', '&lt;')
		.replaceAll('>', '&gt;');

const getUsageMarkup = (item: ProjectItem) => {
	const sample = escapeHtml(item.sampleText);
	const className = `font-${item.familyId}`;
	if (usesNameLigatures(item)) {
		return `<span class="${className}" aria-hidden="true">${sample}</span>`;
	}
	if (isPunctuationFamily(item)) {
		return `<p class="${className}">${sample}</p>`;
	}
	if (isDigitalFamily(item)) {
		return `<span class="${className}">${sample}</span>`;
	}
};

const getProjectCss = (items: ProjectItem[]) => {
	const licenses = items
		.map(
			(item) =>
				`/* ${item.displayName}: ${
					item.license.verified && item.license.id
						? `${item.license.id} (registry verified)`
						: 'license not verified'
				} */`,
		)
		.join('\n');
	const imports = items
		.map((item) => `@import url('${getCdnUrl(item)}');`)
		.join('\n');
	const usage = items.map(getUsageBlock).join('\n\n');
	return `/* Generated by Fontsource Font Set */\n${licenses}\n${imports}\n\n${usage}\n`;
};

export {
	getCdnUrl,
	getFontStack,
	getProjectCss,
	getSelectedCssFiles,
	getUsageBlock,
	getUsageMarkup,
	getUsageNote,
	hasSymbolCatalog,
	isDigitalFamily,
	usesNameLigatures,
};
