# fly.toml app configuration file generated for fontsource on 2023-05-20T03:14:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fontsource"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[env]
PRIMARY_REGION = "nrt"

[deploy]
strategy = "bluegreen"

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "requests"
hard_limit = 100
soft_limit = 60

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "15s"
restart_limit = 5

[[services.http_checks]]
interval = "30s"
timeout = "2s"
grace_period = "15s"
restart_limit = 0
method = "get"
path = "/docs/getting-started/introduction" # Don't hit main route as that burns algolia quota
protocol = "http"
