# fly.toml app configuration file generated for fontsource-staging on 2023-05-20T03:28:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fontsource-staging"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true
enable_consul = true

[env]
PRIMARY_REGION = "nrt"

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 60
soft_limit = 45

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "15s"
restart_limit = 5

[[services.http_checks]]
interval = "30s"
timeout = "2s"
grace_period = "15s"
restart_limit = 0
method = "get"
path = "/docs/getting-started/introduction"
protocol = "http"
