#:schema node_modules/wrangler/config-schema.json
name = "fontsource-website"

main = "./server.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-26"

[assets]
binding = "ASSETS"
directory = "./build/client"

[build]
command = "bun run build"

[[kv_namespaces]]
binding = "ALGOLIA"
id = "1705b67984ae42a29a2c7cb8102ff730"
