#:schema node_modules/wrangler/config-schema.json
name = "fontsource-website"

main = "./workers/app.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-08-15"

[assets]
binding = "ASSETS"
directory = "./build/client"

[[kv_namespaces]]
binding = "ALGOLIA"
id = "1705b67984ae42a29a2c7cb8102ff730"
