#:schema node_modules/wrangler/config-schema.json
name = "fontsource-website"

main = "./workers/app.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-08-15"

[placement]
mode = "smart"

[cache]
enabled = true

[vars]
BETTER_AUTH_URL = "https://fontsource.org"

[[d1_databases]]
binding = "APP_DB"
database_name = "fontsource-app"

[secrets]
required = [
  "BETTER_AUTH_SECRET",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "GITHUB_CLIENT_ID",
  "GITHUB_CLIENT_SECRET",
]

[[services]]
binding = "API"
service = "fontsource-api"

[assets]
binding = "ASSETS"
directory = "./build/client"
html_handling = "drop-trailing-slash"

[[kv_namespaces]]
binding = "ALGOLIA"
id = "1705b67984ae42a29a2c7cb8102ff730"
