#:schema node_modules/wrangler/config-schema.json
name = "fontsource-website"

main = "./server.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-26"

[assets]
directory = "./build/client"

[build]
command = "bun run build"
