version: '3.8'

services:
  app:
    container_name: fontsource-api
    build: .
    ports:
      - '443:8080'
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27018:27017'
    logging:
      driver: 'none'
