name: Build and Release [Weekly]

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          
      - name: Install packages
        run: yarn

      - name: Fetch API
        run: npm explore google-font-metadata -- yarn parser:gen $GOOGLE_API_KEY
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Parse APIv1
        run: yarn parser:v1

      - name: Parse APIv2
        run: yarn parser:v2

      - name: Parse Variable
        run: yarn parser:variable

      - name: Build fonts
        run: yarn build:google

      - name: Generate fontlist
        run: yarn util:fontlist

      - name: Generate Algolia index
        run: yarn util:algolia
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}

      - name: Format files
        run: yarn format

      - name: Stage, commit and push files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "fontsource-bot"
          commit_user_email: "83556432+fontsource-bot@users.noreply.github.com"
          commit_author: "fontsource-bot <83556432+fontsource-bot@users.noreply.github.com>" 
          commit_message: "chore(build): update packages [Weekly $GITHUB_RUN_NUMBER]"
        continue-on-error: true

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: npm run deploy:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
