name: Registry

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Fontsource
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: fontsource/fontsource
          ref: main

      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          path: font-files
          sparse-checkout: sources

      - name: Setup
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Check
        run: pnpm --filter '@fontsource-utils/registry' check:font-files "$GITHUB_WORKSPACE/font-files"
