name: Release

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Enable PNPM
        uses: pnpm/action-setup@v2

      - name: Set node version to 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: cs
        uses: changesets/action@v1
        with:
          version: "pnpm run ci:version"
          publish: "pnpm run ci:publish"
          commit: "chore: release versions"
          title: "Release 🎉"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Dispatch Dependency Update PR to font-files
        if: steps.cs.outputs.published
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          repository: fontsource/font-files
          event-type: update-deps
