name: Website Deploy
on:
  push:
    branches:
      - main
    paths:
      - "website/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    if: github.repository == 'fontsource/fontsource'
    defaults:
      run:
        working-directory: website

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Enable PNPM
        uses: pnpm/action-setup@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Run lints
        run: pnpm run lint

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_PROD_TOKEN }}
