name: Website Deploy
on:
  push:
    branches:
      - website

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only

      - name: Trigger DB updates
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://beta.fontsource.org/actions/update"
          method: "POST"
          bearerToken: ${{ secrets.WESBITE_UPDATE_TOKEN }}
          data: '{"fonts": true, "algolia": true, "download": true, "axisRegistry": true}'
