name: Website Staging Deploy
on:
  pull_request:
    branches:
      - main
    paths:
      - "website/**"
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment:
      name: staging-${{ github.event.number }}
      url: https://staging.fontsource.org/
    concurrency:
      group: staging
    defaults:
      run:
        working-directory: website

    steps:
      - uses: actions/checkout@v3

      - name: Enable PNPM
        uses: pnpm/action-setup@v2

      - name: Set node version to 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Run lints
        run: pnpm run lint

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_STAGING_TOKEN }}

      - name: Trigger DB updates
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://staging.fontsource.org/actions/update"
          method: "POST"
          bearerToken: ${{ secrets.WEBSITE_UPDATE_TOKEN }}
          data: '{"download": true, "axisRegistry": true, "docs": true}'
          timeout: 300000

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "Deployed to staging: https://staging.fontsource.org/"
          only_create: true
